function [] = status_printer(status, key, value)
    switch key
        case 'skope'
            status.skope = value;
        case 'currents'
            status.currents = value;
        case 'write'
            status.write = value;
        case 'count'
            status.count = value;
        case 'time'
            status.uptime = status.starttime - value;
    end
    
    status_string = sprintf(['\nAcquiring Skope data: %s' ...
                             '\nCalculating currents: %s' ...
                             '\nWriting shim values : %s' ...
                             '\nCount               : %d' ...
                             '\nUptime              : %s\n'], ...
                             status.skope, ...
                             status.currents, ...
                             status.write, ...
                             status.count, ...
                             status.uptime);

    fprintf([repmat('\b',1,numel(status_string)) '%s'],status_string);
end